### PR TITLE
Update Model Example Configuration

### PR DESCRIPTION
**Pull request by daniel-de-wit**

### CODE REVIEW

**Comment by czim** [comment]
What's wrong with using the shorthand syntax in the example?

**Comment by daniel-de-wit** [comment]
Seems an array is expected:

`Cannot instantiate data object 'Czim\CmsModels\ModelInformation\Data\ModelReferenceData' with non-array data for key 'reference'`

**Comment by czim** [comment]
Ouch, that looks like a bug. I'll look into it and see if I can't make the shorthand syntax work.

**Comment by czim** [comment]
The short-hand format is now supported, so the documentation can stay as-is.

**Pull request closed without merging**
